export const themes = {
  galactic: {
    id: 'galactic',
    name: 'Galactic Neon',
    bg: 'bg-gradient-to-br from-[#0a0a2e] via-[#1a0a4e] to-[#0a1a3e]',
    bgAnimate: 'animate-gradient',
    card: 'bg-white/10 backdrop-blur-xl border border-white/20',
    cardHover: 'hover:bg-white/15',
    accent: '#a855f7',
    accentClass: 'bg-purple-500',
    glow: '0 0 30px rgba(168,85,247,0.5)',
    text: 'text-white',
    textMuted: 'text-white/70',
    button: 'bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500',
    buttonSecondary: 'bg-white/20 hover:bg-white/30',
    timerColor: '#a855f7',
    timerBg: '#a855f720',
    nav: 'bg-black/40 backdrop-blur-xl border-t border-white/10',
    starColor: '#fbbf24',
    emoji: '🌌',
  },
  candy: {
    id: 'candy',
    name: 'Candy Pastel',
    bg: 'bg-gradient-to-br from-[#fce4ec] via-[#f8e8f8] to-[#e8f4ff]',
    bgAnimate: '',
    card: 'bg-white/70 backdrop-blur-xl border border-white/90',
    cardHover: 'hover:bg-white/80',
    accent: '#ec4899',
    accentClass: 'bg-pink-400',
    glow: '0 0 30px rgba(236,72,153,0.3)',
    text: 'text-gray-800',
    textMuted: 'text-gray-500',
    button: 'bg-gradient-to-r from-pink-400 to-violet-400 hover:from-pink-300 hover:to-violet-300',
    buttonSecondary: 'bg-pink-100 hover:bg-pink-200 text-pink-700',
    timerColor: '#ec4899',
    timerBg: '#ec489920',
    nav: 'bg-white/70 backdrop-blur-xl border-t border-pink-200',
    starColor: '#f59e0b',
    emoji: '🍭',
  },
  eco: {
    id: 'eco',
    name: 'Éco-Forêt',
    bg: 'bg-gradient-to-br from-[#1b4332] via-[#2d6a4f] to-[#1b5e42]',
    bgAnimate: '',
    card: 'bg-white/15 backdrop-blur-xl border border-white/25',
    cardHover: 'hover:bg-white/20',
    accent: '#74c69d',
    accentClass: 'bg-emerald-400',
    glow: '0 0 30px rgba(116,198,157,0.4)',
    text: 'text-white',
    textMuted: 'text-white/70',
    button: 'bg-gradient-to-r from-emerald-500 to-teal-500 hover:from-emerald-400 hover:to-teal-400',
    buttonSecondary: 'bg-white/20 hover:bg-white/30',
    timerColor: '#74c69d',
    timerBg: '#74c69d20',
    nav: 'bg-black/30 backdrop-blur-xl border-t border-white/10',
    starColor: '#fbbf24',
    emoji: '🌿',
  },
} as const;

export type ThemeId = keyof typeof themes;
export type Theme = typeof themes[ThemeId];
